import type { Metadata } from "next";
import { Bai_Jamjuree, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavigationBar from "@/components/navbar";
import SmoothScroll from "@/components/smoothscroll";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-test",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Fahem Khakiki Khaya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SmoothScroll>
            {/* <NavigationBar /> */}
            {children}
          </SmoothScroll>
        </ThemeProvider>
      </body>
    </html>
  );
}
